version: '3.2'

services:

  json-server:
    image: vimagick/json-server
    command: -H 172.28.1.2 -p 3000 -w db.json
    container_name: json_server
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data
    restart: always
    networks:
      testing_net:
        ipv4_address: 172.28.1.2

  localstack:
    image: localstack/localstack:latest
    container_name: localstack_integration
    ports:
      - "4567:4567"
      - "4574:4574"
      - "8080:8080"
    environment:
      - SERVICES=lambda, apigateway
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_REMOTE_DOCKER=true
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PORT_WEB_UI=8080
    volumes:
      - /tmp/localstack:/tmp/localstack
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      testing_net:
        ipv4_address: 172.28.1.3
    depends_on:
      - json-server


networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16