version: '3.2'

services:

  localstack_events_lambda:
    image: localstack/localstack:latest
    ports:
      - '4574:4574'
      - '4587:4587'
      - '8000:8080'
    environment:
      - SERVICES=lambda, events
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_REMOTE_DOCKER=true
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /tmp/localstack:/tmp/localstack
      - '/var/run/docker.sock:/var/run/docker.sock'
